Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2021-08, with the labels that each got.

#23 Add lock template for handling topic property locking
  game/definitions.rpy
Labels: bug, Awaiting Testing

#32 Fix issue with `.get` still being used
  game/definitions.rpy
Labels: bug

#33 Add formal filter methods
  game/definitions.rpy
  game/script-ch30.rpy
  game/script-farewells.rpy
  game/script-greetings.rpy
  game/splash.rpy
  game/topic-handler.rpy
Labels: Awaiting Testing, Needs Code Review

#36 Pets topic bundle and various tweaks
  game/definitions.rpy
  game/gui.rpy
  game/mod_assets/sfx/select_confirm.mp3
  game/mod_assets/sfx/select_hover.mp3
  game/screenshots.rpy
  game/script-farewells.rpy
  game/script-topics.rpy
Labels: Awaiting Testing, Needs Code Review

#39 Lifestyle/staying healthy topic bundle
  game/definitions.rpy
  game/script-ch30.rpy
  game/script-topics.rpy
  game/splash.rpy
Labels: Awaiting Testing

#43 Admissions
  game/definitions.rpy
  game/script-admissions.rpy
  game/script-ch30.rpy
  game/script-farewells.rpy
  game/script-greetings.rpy
  game/script-topics.rpy
  game/splash.rpy
  game/topic-handler.rpy
Labels: Awaiting Testing, Needs Code Review
