Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2021-10, with the labels that each got.

#62 Fashion topic
  game/script-topics.rpy
Labels: Needs Code Review, Needs Dialogue Review

#72 Nickname functionality
  game/definitions.rpy
  game/screenshots.rpy
  game/script-admissions.rpy
  game/script-ch30.rpy
  game/script-nicknames.rpy
  game/script-topics.rpy
Labels: Awaiting Testing, Needs Code Review, Needs Dialogue Review

#88 Fix return crashes + `m` say character
  game/script-ch30.rpy
Labels: bug, Awaiting Testing
