Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2021-11, with the labels that each got.

#99 Use a functional approach for screenshot handling
  game/definitions.rpy
  game/screenshots.rpy
  game/script-topics.rpy
Labels: Documentation, Awaiting Testing, Needs Code Review

#98 Natsuki and work life balance topic
  game/script-topics.rpy
Labels: Needs Code Review, Needs Dialogue Review

#94 Natsuki and headphones topic
  game/script-topics.rpy
Labels: Needs Code Review, Needs Dialogue Review

#70 Natsuki and horror topic
  game/script-topics.rpy
Labels: Needs Code Review, Needs Dialogue Review

#107 Topic mechanic bug fixes
  game/script-ch30.rpy
  game/zz_hotkey_buttons.rpy
Labels: Bug, High Priority

#89 Apologies
  game/definitions.rpy
  game/image-placeholders.rpy
  game/keymaps.rpy
  game/mod_assets/backgrounds/placeholder_sky_day.png
  game/mod_assets/buttons/choice_hover_blank.png
  game/mod_assets/buttons/choice_hover_fold.png
  game/mod_assets/natsuki/placeholder_neutral.png
  game/mod_assets/natsuki/placeholder_plead.png
  game/mod_assets/natsuki/placeholder_sad.png
  game/mod_assets/natsuki/placeholder_smile.png
  game/mod_assets/natsuki/placeholder_sparkle.png
  game/mod_assets/natsuki/placeholder_unamused.png
  game/mod_assets/natsuki/placeholder_wink.png
  game/python-packages/pprint/__init__.py
  game/screens.rpy
  game/script-admissions.rpy
  game/script-apologies.rpy
  game/script-ch30.rpy
  game/script-farewells.rpy
  game/script-greetings.rpy
  game/script-nicknames.rpy
  game/script-screenshots.rpy
  game/script-topics.rpy
  game/splash.rpy
  game/topic-handler.rpy
  game/transform-definitions.rpy
Labels: Awaiting Testing, Needs Code Review, Needs Dialogue Review, High Priority

#108 Apology tweak and fix NatNat's fypo
  game/script-ch30.rpy
Labels: Bug, Needs Code Review
