Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2022-03, with the labels that each got.

#187 Add out of topics dlg.
  game/script-ch30.rpy
  game/script-topics.rpy
Labels: Enhancement

#189 Added lightning fear topic dlg.
  game/gui.rpy
  game/screens.rpy
  game/script-ch30.rpy
  game/script-topics.rpy
  game/zz_hotkey_buttons.rpy
Labels: Enhancement

#191 Added drowsiness topic dlg
  game/definitions.rpy
  game/mod_assets/sfx/chair_in.ogg
  game/mod_assets/sfx/chair_out.ogg
  game/mod_assets/sfx/chair_out_in.ogg
  game/script-topics.rpy
Labels: Enhancement

#198 Adjusted regex for "eja" strings
  game/definitions.rpy
Labels: Bug, Low Priority

#214 [Topic] Proper Hygiene
  game/script-topics.rpy
Labels: Enhancement

#188 Add manga introduction/event framework.
  game/definitions.rpy
  game/mod_assets/natsuki/desk/table-normal.png
  game/mod_assets/props/parfait_manga_held.png
  game/mod_assets/props/poetry_attempt.png
  game/mod_assets/sfx/page_turn.ogg
  game/mod_assets/sfx/paper_crumple.ogg
  game/mod_assets/sfx/paper_throw.ogg
  game/script-ch30.rpy
  game/script-events.rpy
  game/sprite-backend.rpy
  game/topic-handler.rpy
Labels: Enhancement

#225 Removed unneeded props
  game/script-events.rpy
Labels: Bug, High Priority

#228 Updated readme
  README.md
Labels: Documentation

#227 Improved checkbox graphics
  game/mod_assets/buttons/check_foreground.png
  game/mod_assets/buttons/check_selected_foreground.png
  game/screens.rpy
Labels: Enhancement

#230 Updated radio button graphics
  game/screens.rpy
Labels: Bug, Enhancement

#194 Add fear of spiders topic
  game/script-topics.rpy
Labels: Enhancement

#180 [Draft] - What do you think about Monika
  game/script-topics.rpy
Labels: Enhancement

#177 [Pool Draft] - "Thoughts on Yuri"
  game/script-topics.rpy
Labels: Enhancement

#179 [Draft] - What do you think of Sayori
  game/script-topics.rpy
Labels: Enhancement
