Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2022-10, with the labels that each got.

#408 Feature/outfit rework
  game/mod_assets/natsuki/sitting/base/head.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_QT_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_autumn_off_shoulder_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_bee_off_shoulder_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_creamsicle_off_shoulder_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_heart_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_hoodie_not_cute/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_hoodie_turtleneck/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_lolita_dress/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_lolita_school_uniform/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_long_sleeved_shirt_nya/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_low_cut_dress/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_nightbloom_off_shoulder_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_nya_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_pastel_goth_overalls/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_qeeb_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_ruffled_swimsuit/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_square_bra/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_striped_off_shoulder_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_sugar_shirt/sitting.png
  game/mod_assets/natsuki/sitting/headgear/jn_headgear_bee_headband/sitting.png
  game/mod_assets/natsuki/sitting/headgear/jn_headgear_black_beanie/sitting.png
  game/mod_assets/natsuki/sitting/headgear/jn_headgear_lolita_hat/sitting.png
  game/mod_assets/natsuki/sitting/headgear/jn_headgear_spiked_headband/sitting.png
  game/mod_assets/natsuki/sitting/necklace/jn_necklace_black_choker/sitting.png
  game/mod_assets/natsuki/sitting/necklace/jn_necklace_spiked_choker/sitting.png
  game/outfits.rpy
Labels: Enhancement, Needs Code Review, Needs Art Review

#410 Review/outfits and hairstyles rework
  game/mod_assets/natsuki/sitting/base/head.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_QT_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_autumn_off_shoulder_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_bee_off_shoulder_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_creamsicle_off_shoulder_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_heart_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_hoodie_not_cute/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_hoodie_turtleneck/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_lolita_dress/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_lolita_school_uniform/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_long_sleeved_shirt_nya/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_low_cut_dress/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_nightbloom_off_shoulder_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_nya_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_pastel_goth_overalls/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_qeeb_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_ruffled_swimsuit/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_square_bra/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_striped_off_shoulder_sweater/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_sugar_shirt/sitting.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_bedhead/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_bedhead/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_bun/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_bun/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_down/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_down/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_down_long/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_down_long/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_high_hoops/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_high_hoops/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_low_bun/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_low_hoops/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_low_hoops/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_messy_bun/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_messy_bun/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_pigtails/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_pigtails/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_pixie_cut/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_pixie_cut/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_ponytail/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_ponytail/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_princess_braids/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_princess_braids/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_super_messy/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_super_messy/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_twin_buns/bangs.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_twintails/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_twintails_long/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_twintails_long/bangs.png
  game/mod_assets/natsuki/sitting/headgear/jn_headgear_bee_headband/sitting.png
  game/mod_assets/natsuki/sitting/headgear/jn_headgear_black_beanie/sitting.png
  game/mod_assets/natsuki/sitting/headgear/jn_headgear_lolita_hat/sitting.png
  game/mod_assets/natsuki/sitting/headgear/jn_headgear_spiked_headband/sitting.png
  game/mod_assets/natsuki/sitting/necklace/jn_necklace_black_choker/sitting.png
  game/mod_assets/natsuki/sitting/necklace/jn_necklace_spiked_choker/sitting.png
  game/outfits.rpy
Labels: Enhancement, Needs Art Review, Artwork

#417 Add hotkeys to the menus
  game/zz_hotkey_buttons.rpy
Labels: Enhancement

#419 Add QAB screen
  game/gui.rpy
  game/screens.rpy
  game/zz_hotkey_buttons.rpy
Labels: Enhancement

#423 Feature/suggest temporary outfit
  game/outfits.rpy
  game/script-ch30.rpy
Labels: Enhancement
