Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2022-04, with the labels that each got.

#258 Added instructions on updating
  README.md
Labels: Documentation

#266 Add safe handling for Xlib import
  game/activity.rpy
  game/script-topics.rpy
Labels: Bug

#231 Reworked affinity mechanics
  game/definitions.rpy
  game/natsuki.rpy
  game/outfits.rpy
  game/random_music.rpy
  game/relationship-handling.rpy
  game/screens.rpy
  game/script-admissions.rpy
  game/script-apologies.rpy
  game/script-ch30.rpy
  game/script-compliments.rpy
  game/script-events.rpy
  game/script-farewells.rpy
  game/script-greetings.rpy
  game/script-introduction.rpy
  game/script-screenshots.rpy
  game/script-snap.rpy
  game/script-topics.rpy
  game/sprite-backend.rpy
  game/zz_hotkey_buttons.rpy
Labels: Enhancement, Needs Code Review, High Priority

#251 New topics bundle
  game/script-topics.rpy
Labels: Enhancement

#249 New intro events bundle
  README.md
  game/definitions.rpy
  game/mod_assets/natsuki/sitting/face/mouth/drink.png
  game/mod_assets/props/a_la_mode_manga_held.png
  game/mod_assets/props/renpy_for_dummies_book_held.png
  game/mod_assets/props/strawberry_milkshake.png
  game/mod_assets/sfx/glass_move.ogg
  game/mod_assets/sfx/straw_sip.ogg
  game/script-events.rpy
  game/sprite-backend.rpy
Labels: Enhancement

#240 Adjustments to frequency cooldown map
  game/preferences.rpy
Labels: Enhancement

#245 API-based weather
  README.md
  game/atmosphere.rpy
  game/custom-music.rpy
  game/definitions.rpy
  game/locations.rpy
  game/mod_assets/backgrounds/atmosphere/clouds/clouds_day_heavy.png
  game/mod_assets/backgrounds/atmosphere/clouds/clouds_day_light.png
  game/mod_assets/backgrounds/atmosphere/clouds/clouds_day_thunder.png
  game/mod_assets/backgrounds/atmosphere/clouds/clouds_night_heavy.png
  game/mod_assets/backgrounds/atmosphere/clouds/clouds_night_light.png
  game/mod_assets/backgrounds/atmosphere/dim/dim_heavy.png
  game/mod_assets/backgrounds/atmosphere/dim/dim_light.png
  game/mod_assets/backgrounds/atmosphere/dim/dim_medium.png
  game/mod_assets/backgrounds/atmosphere/particles/rain.png
  game/mod_assets/backgrounds/atmosphere/particles/snow.png
  game/mod_assets/backgrounds/atmosphere/sky/sky_day_overcast.png
  game/mod_assets/backgrounds/atmosphere/sky/sky_day_rain.png
  game/mod_assets/backgrounds/atmosphere/sky/sky_day_snow.png
  game/mod_assets/backgrounds/atmosphere/sky/sky_day_sunny.png
  game/mod_assets/backgrounds/atmosphere/sky/sky_day_thunder.png
  game/mod_assets/backgrounds/atmosphere/sky/sky_night_overcast.png
  game/mod_assets/backgrounds/atmosphere/sky/sky_night_rain.png
  game/mod_assets/backgrounds/atmosphere/sky/sky_night_sunny.png
  game/mod_assets/backgrounds/atmosphere/sky/sky_night_thunder.png
  game/mod_assets/backgrounds/beach/mirage.png
  game/mod_assets/backgrounds/cabin/cabin.png
  game/mod_assets/backgrounds/cemetary/cemetary.png
  game/mod_assets/backgrounds/classroom/classroom-night.png
  game/mod_assets/backgrounds/classroom/sky_day_overcast.png
  game/mod_assets/backgrounds/classroom/sky_day_rain.png
  game/mod_assets/backgrounds/classroom/sky_day_sunny.png
  game/mod_assets/backgrounds/classroom/sky_day_thunder.png
  game/mod_assets/backgrounds/kitchen/kitchen.png
  game/mod_assets/backgrounds/mall/bakery.png
  game/mod_assets/backgrounds/mall/clothesstore.png
  game/mod_assets/backgrounds/mall/mall.png
  game/mod_assets/backgrounds/mall/mangastore.png
  game/mod_assets/backgrounds/park/park.png
  game/mod_assets/backgrounds/pool/pool.png
  game/mod_assets/backgrounds/residential/house_night.png
  game/mod_assets/backgrounds/residential/residential_night.png
  game/mod_assets/natsuki/sitting/face/mouth/blep.png
  game/natsuki.rpy
  game/outfits.rpy
  game/preferences.rpy
  game/screens.rpy
  game/script-ch30.rpy
  game/script-events.rpy
  game/script-introduction.rpy
  game/script-topics.rpy
  game/sprite-backend.rpy
  lib/windows-i686/_ssl.pyd
  lib/windows-i686/ssl.pyo
Labels: Enhancement, High Priority, Reserved

#274 Tears and emotes
  game/definitions.rpy
  game/mod_assets/natsuki/sitting/emote/question_mark.png
  game/mod_assets/natsuki/sitting/face/eyes/circle_tears.png
  game/mod_assets/natsuki/sitting/face/eyes/closed_happy.png
  game/mod_assets/natsuki/sitting/face/eyes/closed_sad.png
  game/mod_assets/natsuki/sitting/face/eyes/look_left.png
  game/mod_assets/natsuki/sitting/face/eyes/look_right.png
  game/mod_assets/natsuki/sitting/face/eyes/squint_left.png
  game/mod_assets/natsuki/sitting/face/eyes/squint_right.png
  game/mod_assets/natsuki/sitting/face/eyes/wink_left.png
  game/mod_assets/natsuki/sitting/face/eyes/wink_right.png
  game/mod_assets/natsuki/sitting/face/mouth/big_smile.png
  game/mod_assets/natsuki/sitting/face/mouth/small_frown.png
  game/mod_assets/natsuki/sitting/face/mouth/small_smile.png
  game/mod_assets/natsuki/sitting/face/tears/double_stream_closed.png
  game/mod_assets/natsuki/sitting/face/tears/double_stream_narrow.png
  game/mod_assets/natsuki/sitting/face/tears/double_stream_regular.png
  game/mod_assets/natsuki/sitting/face/tears/dried.png
  game/mod_assets/natsuki/sitting/face/tears/single_pooled_closed.png
  game/mod_assets/natsuki/sitting/face/tears/single_pooled_narrow.png
  game/mod_assets/natsuki/sitting/face/tears/single_pooled_regular.png
  game/mod_assets/natsuki/sitting/face/tears/single_stream_closed.png
  game/mod_assets/natsuki/sitting/face/tears/single_stream_narrow.png
  game/mod_assets/natsuki/sitting/face/tears/single_stream_regular.png
  game/mod_assets/natsuki/sitting/face/tears/spritz.png
  game/mod_assets/natsuki/sitting/face/tears/wink_pooled_left.png
  game/mod_assets/natsuki/sitting/face/tears/wink_pooled_right.png
  game/script-apologies.rpy
  game/script-events.rpy
  game/script-farewells.rpy
  game/script-greetings.rpy
  game/script-topics.rpy
  game/sprite-backend.rpy
Labels: Enhancement, High Priority

#282 Removed DDLC anticheat
  game/splash.rpy
Labels: Needs Code Review

#283 Fix intro events crash
  game/script-events.rpy
Labels: Bug, Needs Code Review, High Priority
