Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2022-11, with the labels that each got.

#436 Update README.md
  README.md
Labels: Documentation

#438 Update README.md
  README.md
Labels: Documentation

#440 Corrected variable checks for talk_impressions_of_the_other_girls
  README.md
  game/script-topics.rpy
Labels: Bug

#443 Remove ability to skip dialogue, enforce pauses
  game/activity.rpy
  game/definitions.rpy
  game/options.rpy
  game/outfits.rpy
  game/random_music.rpy
  game/script-ch30.rpy
  game/script-events.rpy
  game/script-greetings.rpy
  game/script-introduction.rpy
  game/script-snap.rpy
  game/script-topics.rpy
  game/zz_data-migrations.rpy
Labels: Bug

#422 Feature/new glasses intro
  game/atmosphere.rpy
  game/definitions.rpy
  game/gui.rpy
  game/mod_assets/natsuki/sitting/eyewear/jn_eyewear_circles/sitting.png
  game/mod_assets/natsuki/sitting/eyewear/jn_eyewear_heart_frames/sitting.png
  game/mod_assets/natsuki/sitting/eyewear/jn_eyewear_rectangular_glasses_black/sitting.png
  game/mod_assets/natsuki/sitting/eyewear/jn_eyewear_rectangular_glasses_red/sitting.png
  game/mod_assets/natsuki/sitting/eyewear/jn_eyewear_round_glasses_black/sitting.png
  game/mod_assets/natsuki/sitting/eyewear/jn_eyewear_round_glasses_brown/sitting.png
  game/mod_assets/natsuki/sitting/eyewear/jn_eyewear_round_glasses_red/sitting.png
  game/mod_assets/natsuki/sitting/eyewear/jn_eyewear_round_sunglasses/sitting.png
  game/mod_assets/overlays/slipped_glasses.png
  game/mod_assets/overlays/slipping_glasses.png
  game/mod_assets/props/glasses_case.png
  game/mod_assets/sfx/camera_shutter.mp3
  game/mod_assets/sfx/camera_shutter.ogg
  game/mod_assets/sfx/card_place.mp3
  game/mod_assets/sfx/card_place.ogg
  game/mod_assets/sfx/card_shuffle.mp3
  game/mod_assets/sfx/card_shuffle.ogg
  game/mod_assets/sfx/clothing_ruffle.mp3
  game/mod_assets/sfx/clothing_ruffle.ogg
  game/mod_assets/sfx/coin_flip.mp3
  game/mod_assets/sfx/coin_flip.ogg
  game/mod_assets/sfx/drawer.mp3
  game/mod_assets/sfx/drawer.ogg
  game/mod_assets/sfx/glasses_case_close.ogg
  game/mod_assets/sfx/glasses_case_open.ogg
  game/mod_assets/sfx/rain_muffled.mp3
  game/mod_assets/sfx/rain_muffled.ogg
  game/mod_assets/sfx/scritch.mp3
  game/mod_assets/sfx/scritch.ogg
  game/mod_assets/sfx/select_confirm.mp3
  game/mod_assets/sfx/select_confirm.ogg
  game/mod_assets/sfx/select_hover.mp3
  game/mod_assets/sfx/select_hover.ogg
  game/mod_assets/sfx/smack.mp3
  game/mod_assets/sfx/smack.ogg
  game/mod_assets/sfx/stationary_rustle_a.ogg
  game/mod_assets/sfx/stationary_rustle_b.ogg
  game/mod_assets/sfx/stationary_rustle_c.ogg
  game/outfits.rpy
  game/script-events.rpy
  game/script-farewells.rpy
  game/script-snap.rpy
Labels: Enhancement

#405 Feature/wintendo switch intro events
  game/definitions.rpy
  game/mod_assets/natsuki/sitting/face/mouth/focus.png
  game/mod_assets/props/twitch/dead/wintendo_twitch_dead_a.png
  game/mod_assets/props/twitch/dead/wintendo_twitch_dead_b.png
  game/mod_assets/props/twitch/gaming/charging/wintendo_twitch_playing_a.png
  game/mod_assets/props/twitch/gaming/charging/wintendo_twitch_playing_b.png
  game/mod_assets/props/twitch/gaming/charging/wintendo_twitch_playing_c.png
  game/mod_assets/props/twitch/gaming/free/wintendo_twitch_playing_a.png
  game/mod_assets/props/twitch/gaming/free/wintendo_twitch_playing_b.png
  game/mod_assets/props/twitch/gaming/free/wintendo_twitch_playing_c.png
  game/mod_assets/props/twitch/held/wintendo_twitch_held_charging.png
  game/mod_assets/props/twitch/held/wintendo_twitch_held_free.png
  game/mod_assets/props/twitch/low_battery/wintendo_twitch_battery_low_a.png
  game/mod_assets/props/twitch/low_battery/wintendo_twitch_battery_low_b.png
  game/mod_assets/sfx/button_mashing_a.ogg
  game/mod_assets/sfx/button_mashing_b.ogg
  game/mod_assets/sfx/button_mashing_c.ogg
  game/mod_assets/sfx/button_tap_a.ogg
  game/mod_assets/sfx/button_tap_b.ogg
  game/mod_assets/sfx/button_tap_c.ogg
  game/mod_assets/sfx/twitch_die.ogg
  game/mod_assets/sfx/twitch_you_lose.ogg
  game/script-events.rpy
  game/sprite-backend.rpy
Labels: Enhancement

#447 Add extra option to talk_school_uniform topic question
  game/script-topics.rpy
Labels: Topic

#454 Feature/unlock cosplay outfits
  game/definitions.rpy
  game/mod_assets/sfx/zipper.ogg
  game/outfits.rpy
  game/screens.rpy
  game/script-events.rpy
  game/script-topics.rpy
Labels: Bug, Enhancement, Needs Code Review, Needs Dialogue Review

#456 Feature/unlockable skater outfit
  game/mod_assets/natsuki/sitting/accessory/jn_accessory_double_white_hairbands/sitting.png
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_skater_shirt/sitting.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_twintails_white_ribbons/back.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_twintails_white_ribbons/bangs.png
  game/mod_assets/natsuki/sitting/necklace/jn_necklace_twirled_choker/sitting.png
  game/outfits.rpy
  game/script-topics.rpy
Labels: Topic

#451 Feature/cardigan outfit
  game/definitions.rpy
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_cosy_cardigan/sitting.png
  game/mod_assets/natsuki/sitting/headgear/jn_headgear_teddy_hairpins/sitting.png
  game/mod_assets/props/hot_chocolate.png
  game/mod_assets/props/hot_chocolate_cold.png
  game/mod_assets/sfx/drink_pour.ogg
  game/mod_assets/sfx/kettle_boil.ogg
  game/mod_assets/sfx/switch_flip.ogg
  game/outfits.rpy
  game/script-ch30.rpy
  game/script-events.rpy
  game/script-farewells.rpy
  game/script-introduction.rpy
Labels: Enhancement

#457 Feature/unlockable off shoulder sweaters
  game/outfits.rpy
  game/script-ch30.rpy
  game/script-farewells.rpy
  game/script-greetings.rpy
  game/script-topics.rpy
Labels: Enhancement, Topic

#462 Feature/bunny pajama
  game/mod_assets/natsuki/sitting/clothes/jn_clothes_bunny_pajamas/sitting.png
  game/mod_assets/natsuki/sitting/hair/jn_hair_super_messy/back.png
  game/mod_assets/natsuki/sitting/headgear/jn_headgear_sleep_mask/sitting.png
  game/outfits.rpy
Labels: Enhancement

#464 Feature/extra functionality
  game/definitions.rpy
  game/mod_assets/buttons/option_disabled.png
  game/mod_assets/extra/headpats/headpat_poof_a.png
  game/mod_assets/extra/headpats/headpat_poof_b.png
  game/mod_assets/extra/headpats/headpat_poof_c.png
  game/mod_assets/extra/headpats/headpat_poof_d.png
  game/mod_assets/extra/headpats/headpat_poof_e.png
  game/mod_assets/extra/headpats/headpats_active_cursor.png
  game/mod_assets/sfx/headpat.ogg
  game/natsuki.rpy
  game/outfits.rpy
  game/plugins.rpy
  game/relationship-handling.rpy
  game/script-headpats.rpy
  game/script-topics.rpy
  game/zz_hotkey_buttons.rpy
Labels: Enhancement
