Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2022-07, with the labels that each got.

#345 Data Migration Framework
  game/options.rpy
  game/screens.rpy
  game/script-ch30.rpy
  game/zz_data-migrations.rpy
Labels: Awaiting Testing, Needs Code Review, Major Update

#350 Fixes braces/brackets in files breaking custom music
  game/custom-music.rpy
  game/definitions.rpy
  game/zz_data-migrations.rpy
Labels: Bug, High Priority

#291 Adjusted logging
  game/natsuki.rpy
Labels: Enhancement, Low Priority

#323 Fear of flying topic
  game/script-greetings.rpy
  game/script-topics.rpy
Labels: Enhancement

#315 Disable Talk, Extras buttons when already in menus
  game/script-ch30.rpy
Labels: Bug, Low Priority

#279 Thoughts on fanart topic
  game/script-topics.rpy
Labels: Enhancement

#313 Ribbons addition to hairstyle topic
  game/script-topics.rpy
Labels: Enhancement

#311 How to interview topic
  game/script-topics.rpy
Labels: Enhancement

#320 Add bullying windup topic
  game/screens.rpy
  game/script-topics.rpy
Labels: Enhancement

#351 Removed screenshot dialogue
  game/script-apologies.rpy
  game/script-ch30.rpy
  game/script-screenshots.rpy
  game/script-topics.rpy
Labels: Enhancement

#358 Fixed some incorrect {nw} tags
  game/script-farewells.rpy
Labels: Bug, High Priority

#359 Fix for prolonged leave not triggering
  game/script-ch30.rpy
  game/script-farewells.rpy
  game/script-greetings.rpy
Labels: Bug

#361 Add wearable outfit reactions
  game/atmosphere.rpy
  game/definitions.rpy
  game/mod_assets/sfx/kiss.ogg
  game/mod_assets/sticker/blank.png
  game/mod_assets/sticker/blank_cheer.png
  game/mod_assets/sticker/normal.png
  game/outfits.rpy
  game/script-ch30.rpy
  game/script-topics.rpy
  game/stickers.rpy
Labels: Enhancement
