Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2022-01, with the labels that each got.

#136 Feature/natsuki and sports topic
  game/script-topics.rpy
Labels: Needs Dialogue Review

#150 Fixed custom music crash
  game/custom-music.rpy
  game/script-topics.rpy
Labels: Bug, Needs Code Review

#152 Natsuki and online shopping topic
  game/script-topics.rpy
Labels: Enhancement

#155 Natsuki and subscriptions topic
  game/script-topics.rpy
Labels: Enhancement

#121 Spritecoding And Dialogue Adjustments
  game/script-topics.rpy
Labels: Needs Dialogue Review
