Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2023-03, with the labels that each got.

#563 Bugfix/prevent multiple game instances
  game/atmosphere.rpy
  game/script-ch30.rpy
  game/zz_data-migrations.rpy
  game/zz_singleton.rpy
Labels: Bug

#558 Feature/staying motivated topic
  game/script-topics.rpy
Labels: Topic

#564 Feature/new hairstyles
  game/mod_assets/natsuki/hair/jn_hair_twintails_braided/sitting/back.png
  game/mod_assets/natsuki/hair/jn_hair_twintails_braided/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_twintails_down/sitting/back.png
  game/mod_assets/natsuki/hair/jn_hair_twintails_down/sitting/bangs.png
  game/outfits.rpy
Labels: Enhancement

#569 Bugfix/activity system linux patch
  game/activity.rpy
Labels: Bug

#571 fixed mistakes in bangs
  game/mod_assets/natsuki/hair/jn_hair_bedhead/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_bun/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_down/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_down_long/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_high_hoops/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_low_bun/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_low_hoops/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_messy_bun/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_pigtails/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_pixie_cut/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_ponytail/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_princess_braids/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_super_messy/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_twin_buns/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_twintails/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_twintails_long/sitting/bangs.png
  game/mod_assets/natsuki/hair/jn_hair_twintails_white_ribbons/sitting/bangs.png
Labels: Bug

#572 Bugfix/random topic logic adjustment
  game/preferences.rpy
  game/screens.rpy
  game/script-ch30.rpy
Labels: Bug

#567 added chocolate_plaid_collection
  game/mod_assets/natsuki/clothes/jn_clothes_chocolate_plaid_dress/arms_crossed_body.png
  game/mod_assets/natsuki/clothes/jn_clothes_chocolate_plaid_dress/arms_crossed_desk.png
  game/mod_assets/natsuki/clothes/jn_clothes_chocolate_plaid_dress/fingers_on_desk.png
  game/mod_assets/natsuki/clothes/jn_clothes_chocolate_plaid_dress/sitting.png
  game/mod_assets/natsuki/headgear/jn_headgear_chocolate_plaid_bow/sitting.png
  game/mod_assets/natsuki/necklace/jn_necklace_golden_necklace/sitting.png
  game/mod_assets/natsuki/sleeves/jn_clothes_chocolate_plaid_dress/arms_crossed_body.png
  game/mod_assets/natsuki/sleeves/jn_clothes_chocolate_plaid_dress/arms_crossed_desk.png
  game/mod_assets/natsuki/sleeves/jn_clothes_chocolate_plaid_dress/fingers_on_desk.png
  game/mod_assets/natsuki/sleeves/jn_clothes_chocolate_plaid_dress/sitting.png
  game/outfits.rpy
  game/script-topics.rpy
Labels: Topic

#570 Bugfix/1.0.3 patch
  game/activity.rpy
  game/preferences.rpy
  game/screens.rpy
  game/script-ch30.rpy
Labels: Bug

#588 Bugfix/custom music not playing on mac
  game/custom-music.rpy
  game/definitions.rpy
  game/script-topics.rpy
Labels: Bug

#589 Bugfix/Not ready yet event condition fix
  game/script-events.rpy
  game/zz_data-migrations.rpy
Labels: Bug

#591 Feature/parfait girls manga prop update
  game/mod_assets/props/parfait_manga_held.png
Labels: Topic, Artwork
