Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2023-05, with the labels that each got.

#670 Fixed missing space in the insecure admission
  game/script-admissions.rpy
Labels: Bug

#671 Bugfix/random music check error
  game/random_music.rpy
Labels: Bug, High Priority

#672 v1.2.1
  README.md
  game/options.rpy
  game/random_music.rpy
  game/script-admissions.rpy
  game/script-topics.rpy
  game/zz_data-migrations.rpy
Labels: Bug, Minor Update

#676 adjusted the grammar
  game/script-idles.rpy
Labels: Bug

#682 added missing word
  game/script-admissions.rpy
Labels: Bug

#685 Bugfix facewear disappearing after restart
  game/outfits.rpy
Labels: Bug

#692 removed an additional space
  game/script-farewells.rpy
Labels: Bug

#687 Bugfix/poems skipped on auto
  game/script-poems.rpy
Labels: Bug

#690 Feature/activity window additions
  game/activity.rpy
Labels: Enhancement

#691 Feature/add prevent out of topic warning
  game/preferences.rpy
  game/script-ch30.rpy
  game/script-topics.rpy
Labels: Enhancement

#686 Bugfix/snap block
  game/script-snap.rpy
  game/script-topics.rpy
  game/sprite-backend.rpy
Labels: Bug, Enhancement

#694 switched two words
  game/script-farewells.rpy
Labels: Bug

#689 Feature/star for new topic indicator
  game/mod_assets/buttons/choice_hover_blank_star.png
  game/screens.rpy
Labels: Enhancement

#698 Bugfix/player nickname false positive
  game/definitions.rpy
Labels: Bug

#699 Feature/greeting farewell mini expansion
  game/script-farewells.rpy
  game/script-greetings.rpy
Labels: Enhancement

#701 Feature/joke expansion v1.2.2
  game/mod_assets/fonts/natsuki.ttf
  game/script-jokes.rpy
Labels: Topic

#702 v1.2.2
  README.md
  game/activity.rpy
  game/definitions.rpy
  game/mod_assets/buttons/choice_hover_blank_star.png
  game/mod_assets/fonts/natsuki.ttf
  game/mod_assets/panels/slider_thumb_small.png
  game/options.rpy
  game/outfits.rpy
  game/preferences.rpy
  game/screens.rpy
  game/script-admissions.rpy
  game/script-ch30.rpy
  game/script-farewells.rpy
  game/script-greetings.rpy
  game/script-idles.rpy
  game/script-jokes.rpy
  game/script-poems.rpy
  game/script-snap.rpy
  game/script-topics.rpy
  game/sprite-backend.rpy
  game/zz_data-migrations.rpy
Labels: Bug, Enhancement, Minor Update

#704 Docs/Update README
  README.md
Labels: Documentation

#713 fixed a typo in the work farewell
  game/script-farewells.rpy
Labels: Bug

#714 Docs/Contribution guidelines and staff list
  .github/workflows/gen-contribs.yml
  README.md
Labels: Documentation

#710 Feature/enable remind no topic warning
  game/script-topics.rpy
Labels: Topic

#723 Bugfix/fix scaling active area issue
  game/script-headpats.rpy
Labels: Bug

#724 Feature/tweak twitch game over intro
  game/script-events.rpy
Labels: Enhancement
