Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2023-11, with the labels that each got.

#823 Fixes a typo in talk_thoughts_on_tea
  game/script-topics.rpy
Labels: Bug

#822 Typo in windup_playing_things_out_loud
  game/script-topics.rpy
Labels: Bug

#829 Bugfix/Blackjack failed player name interpolation
  game/script-blackjack.rpy
Labels: Bug

#828 Bugfix/Renpy for dummies clone
  game/desk-items.rpy
  game/script-events.rpy
  game/script-idles.rpy
Labels: Bug

#831 v1.3.2
  README.md
  game/desk-items.rpy
  game/options.rpy
  game/script-blackjack.rpy
  game/script-events.rpy
  game/script-idles.rpy
  game/script-topics.rpy
  game/zz_data-migrations.rpy
Labels: Bug, High Priority, Minor Update

#836 Bugfix/Birthday tease error
  game/script-ch30.rpy
  game/script-events.rpy
Labels: Bug

#838 v1.3.3
  README.md
  game/options.rpy
  game/script-ch30.rpy
  game/script-events.rpy
  game/zz_data-migrations.rpy
Labels: Bug, Minor Update

#843 Bugfix/custom outfits unlock error
  game/script-blackjack.rpy
  game/script-ch30.rpy
  game/script-topics.rpy
Labels: Bug

#844 Bugfix/qt sweater issue
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/arms_crossed_body.png
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/arms_crossed_desk.png
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/finger_touching.png
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/fingers_on_desk.png
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/hand_on_chin.png
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/pointy_finger.png
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/sitting.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/arms_crossed_body.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/arms_crossed_desk.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/finger_touching.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/fingers_on_desk.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/hand_on_chin.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/pointy_finger.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/sitting.png
  game/zz_data-migrations.rpy
Labels: Bug, OS:Linux, OS:MacOS

#845 Bugfix/animation delay fix
  game/natsuki.rpy
  game/preferences.rpy
  game/script-blackjack.rpy
  game/script-ch30.rpy
  game/script-headpats.rpy
  game/script-jokes.rpy
  game/script-snap.rpy
  game/sprite-backend.rpy
  game/threading.rpy
  game/transform-definitions.rpy
  game/zz_hotkey_buttons.rpy
Labels: Bug

#846 Bugfix/function not callable logging
  game/script-snap.rpy
Labels: Bug

#847 v1.3.4
  README.md
  game/definitions.rpy
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/arms_crossed_body.png
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/arms_crossed_desk.png
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/finger_touching.png
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/fingers_on_desk.png
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/hand_on_chin.png
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/pointy_finger.png
  game/mod_assets/natsuki/clothes/jn_clothes_qt_sweater/sitting.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/arms_crossed_body.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/arms_crossed_desk.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/finger_touching.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/fingers_on_desk.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/hand_on_chin.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/pointy_finger.png
  game/mod_assets/natsuki/sleeves/jn_clothes_qt_sweater/sitting.png
  game/natsuki.rpy
  game/options.rpy
  game/preferences.rpy
  game/script-blackjack.rpy
  game/script-ch30.rpy
  game/script-headpats.rpy
  game/script-jokes.rpy
  game/script-snap.rpy
  game/script-topics.rpy
  game/sprite-backend.rpy
  game/threading.rpy
  game/transform-definitions.rpy
  game/zz_data-migrations.rpy
  game/zz_hotkey_buttons.rpy
Labels: Bug, Documentation, Dialogue, Minor Update
