Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2023-06, with the labels that each got.

#726 Feature/gold necklace standalone
  game/mod_assets/natsuki/necklace/jn_necklace_tight_golden_necklace/sitting.png
  game/outfits.rpy
  game/script-topics.rpy
  game/zz_data-migrations.rpy
Labels: Artwork

#730 Feature/seen before jokes
  game/custom-music.rpy
  game/definitions.rpy
  game/desk-items.rpy
  game/mod_assets/icons/custom_music.png
  game/mod_assets/icons/joke_book.png
  game/mod_assets/natsuki/etc/empty.png
  game/mod_assets/props/card_pack.png
  game/mod_assets/props/laptop.png
  game/mod_assets/props/plush/hammie/hammie_damaged.png
  game/mod_assets/props/plush/hammie/hammie_fixed.png
  game/natsuki.rpy
  game/screens.rpy
  game/script-admissions.rpy
  game/script-ch30.rpy
  game/script-jokes.rpy
  game/script-snap.rpy
  game/script-topics.rpy
  game/sprite-backend.rpy
Labels: Topic

#734 Feature/laptop idle
  game/definitions.rpy
  game/mod_assets/sfx/laptop_close.ogg
  game/script-idles.rpy
Labels: Topic

#733 Feature/topic did you have pets refresh
  game/custom-music.rpy
  game/script-topics.rpy
  game/sprite-backend.rpy
  game/zz_data-migrations.rpy
Labels: Topic

#736 Feature/additional jokes
  game/script-jokes.rpy
Labels: Enhancement

#732 Feature/additional menu icons
  game/mod_assets/icons/admissions.png
  game/mod_assets/icons/apologies.png
  game/mod_assets/icons/compliments.png
  game/outfits.rpy
  game/preferences.rpy
  game/screens.rpy
  game/script-admissions.rpy
  game/script-apologies.rpy
  game/script-compliments.rpy
Labels: Artwork

#741 Feature/activity system recording app support
  game/activity.rpy
  game/definitions.rpy
  game/mod_assets/natsuki/face/eyes/sitting/down_left.png
  game/mod_assets/natsuki/face/eyes/sitting/down_right.png
  game/natsuki.rpy
  game/outfits.rpy
  game/script-ch30.rpy
  game/script-headpats.rpy
  game/script-idles.rpy
  game/script-introduction.rpy
  game/script-nicknames.rpy
  game/script-topics.rpy
  game/sprite-backend.rpy
Labels: Enhancement

#744 Bugfix/outfit name false positive
  README.md
  game/definitions.rpy
  game/options.rpy
  game/outfits.rpy
  game/zz_data-migrations.rpy
Labels: Bug, High Priority

#745 v1.2.3
  README.md
  game/definitions.rpy
  game/options.rpy
  game/outfits.rpy
  game/zz_data-migrations.rpy
Labels: Bug, Minor Update

#747 Feature/additional jokes
  game/script-jokes.rpy
  game/script-topics.rpy
Labels: Enhancement

#750 Adjusted arm pose
  game/script-greetings.rpy
Labels: Bug

#746 Feature/topic service animals refresh
  game/script-topics.rpy
Labels: Topic

#751 Feature/idle math attempts
  game/desk-items.rpy
  game/mod_assets/props/math_attempt.png
  game/mod_assets/props/poem_on_desk.png
  game/mod_assets/props/poetry_attempt.png
  game/script-events.rpy
  game/script-idles.rpy
  game/sprite-backend.rpy
Labels: Topic

#754 Feature/potted plant intro
  game/desk-items.rpy
  game/mod_assets/props/plants/sanjo/sanjo.png
  game/mod_assets/props/plants/sanjo/sanjo_bloom.png
  game/mod_assets/sfx/light_switch.ogg
  game/natsuki.rpy
  game/script-admissions.rpy
  game/script-ch30.rpy
  game/script-events.rpy
  game/script-greetings.rpy
  game/script-idles.rpy
  game/script-topics.rpy
  game/sprite-backend.rpy
  game/topic-handler.rpy
  game/zz_data-migrations.rpy
Labels: Enhancement

#757 Feature/idle plantcare
  game/desk-items.rpy
  game/mod_assets/props/plant_care_book_held.png
  game/mod_assets/props/watering_can.png
  game/natsuki.rpy
  game/script-events.rpy
  game/script-greetings.rpy
  game/script-idles.rpy
Labels: Enhancement
