Repository Just-Natsuki-Team/NatsukiModDev, pull requests merged in 2023-04, with the labels that each got.

#594 Feature/daily jokes
  game/definitions.rpy
  game/mod_assets/props/joke_book_held.png
  game/natsuki.rpy
  game/script-ch30.rpy
  game/script-jokes.rpy
  game/script-poems.rpy
  game/script-topics.rpy
Labels: Topic

#598 Feature/easter 23
  game/atmosphere.rpy
  game/mod_assets/backgrounds/atmosphere/particles/cherry_blossom_day.png
  game/mod_assets/backgrounds/atmosphere/particles/cherry_blossom_night.png
  game/mod_assets/backgrounds/atmosphere/sky/sky_day_blossom.png
  game/mod_assets/natsuki/accessory/jn_accessory_cherry_blossom_hairpin/sitting.png
  game/mod_assets/natsuki/accessory/jn_accessory_fried_egg_hairpin/sitting.png
  game/mod_assets/natsuki/clothes/jn_clothes_cherry_blossom_dress/arms_crossed_body.png
  game/mod_assets/natsuki/clothes/jn_clothes_cherry_blossom_dress/arms_crossed_desk.png
  game/mod_assets/natsuki/clothes/jn_clothes_cherry_blossom_dress/fingers_on_desk.png
  game/mod_assets/natsuki/clothes/jn_clothes_cherry_blossom_dress/sitting.png
  game/mod_assets/natsuki/clothes/jn_clothes_chick_dress/arms_crossed_body.png
  game/mod_assets/natsuki/clothes/jn_clothes_chick_dress/arms_crossed_desk.png
  game/mod_assets/natsuki/clothes/jn_clothes_chick_dress/fingers_on_desk.png
  game/mod_assets/natsuki/clothes/jn_clothes_chick_dress/sitting.png
  game/mod_assets/natsuki/necklace/jn_necklace_bunny_necklace/sitting.png
  game/mod_assets/natsuki/sleeves/jn_clothes_cherry_blossom_dress/arms_crossed_body.png
  game/mod_assets/natsuki/sleeves/jn_clothes_cherry_blossom_dress/arms_crossed_desk.png
  game/mod_assets/natsuki/sleeves/jn_clothes_cherry_blossom_dress/fingers_on_desk.png
  game/mod_assets/natsuki/sleeves/jn_clothes_cherry_blossom_dress/sitting.png
  game/mod_assets/natsuki/sleeves/jn_clothes_chick_dress/arms_crossed_body.png
  game/mod_assets/natsuki/sleeves/jn_clothes_chick_dress/arms_crossed_desk.png
  game/mod_assets/natsuki/sleeves/jn_clothes_chick_dress/fingers_on_desk.png
  game/mod_assets/natsuki/sleeves/jn_clothes_chick_dress/sitting.png
  game/outfits.rpy
  game/script-events.rpy
  game/script-jokes.rpy
  game/script-poems.rpy
  game/script-topics.rpy
  game/zz_data-migrations.rpy
Labels: Bug, Topic

#600 v1.1.1
  game/options.rpy
  game/script-ch30.rpy
  game/zz_data-migrations.rpy
Labels: Bug

#616 Bugfix/Stop daily joke typo
  game/script-topics.rpy
Labels: Bug

#618 Bugfix/History lines text cutoff and gitignore update
  .gitignore
  game/gui.rpy
  game/options.rpy
  game/screens.rpy
  game/zz_data-migrations.rpy
Labels: Bug

#617 Bugfix/Custom music not playing vanilla BGMs
  game/custom-music.rpy
  game/random_music.rpy
Labels: Bug

#619 Feature/Vibing idle
  game/mod_assets/natsuki/headgear/jn_headgear_cat_headphones/sitting.png
  game/mod_assets/props/music/music_notes_a.png
  game/mod_assets/props/music/music_notes_b.png
  game/mod_assets/props/music/music_notes_c.png
  game/mod_assets/props/music/music_notes_d.png
  game/outfits.rpy
  game/script-ch30.rpy
  game/script-events.rpy
  game/script-idles.rpy
  game/script-jokes.rpy
  game/sprite-backend.rpy
Labels: Topic

#625 Bugfix/Headpat cursor on menu
  game/screens.rpy
Labels: Bug

#626 Feature/updating expressions
  game/mod_assets/natsuki/face/eyebrows/sitting/concerned.png
  game/mod_assets/natsuki/face/eyes/sitting/down.png
  game/mod_assets/natsuki/face/eyes/sitting/think_left.png
  game/mod_assets/natsuki/face/eyes/sitting/think_right.png
  game/mod_assets/natsuki/face/eyes/sitting/up.png
  game/sprite-backend.rpy
Labels: Enhancement

#628 Bugfix/topics idles after menu
  game/script-ch30.rpy
Labels: Bug

#629 Bugfix/Update sweat sprite layer
  game/sprite-backend.rpy
Labels: Bug

#631 polished black_choker
  game/mod_assets/natsuki/necklace/jn_necklace_black_choker/sitting.png
Labels: Artwork

#634 Feature/custom music on boot
  game/custom-music.rpy
  game/random_music.rpy
  game/script-ch30.rpy
  game/script-greetings.rpy
Labels: Enhancement

#632 Feature/fitting clothing topic
  game/locations.rpy
  game/mod_assets/furniture/classroom/beanbag_day.png
  game/mod_assets/furniture/classroom/beanbag_night.png
  game/outfits.rpy
  game/screens.rpy
  game/script-topics.rpy
Labels: Topic

#630 Feature/more daily jokes
  game/script-jokes.rpy
Labels: Topic

#637 Feature/favourite subject topic
  game/script-topics.rpy
Labels: Topic

#643 Tweaks/adjusts menu spacing
  game/gui.rpy
  game/screens.rpy
Labels: Bug, Enhancement

#646 Bugfix/disable auto on idle
  game/definitions.rpy
Labels: Bug

#650 Bugfix/incorrect name on birthday greet
  game/script-events.rpy
Labels: Bug

#651 Feature/Update checkbox graphic
  game/mod_assets/buttons/check_selected_foreground.png
Labels: Enhancement

#652 Feature/can you draw topic
  game/activity.rpy
  game/script-topics.rpy
Labels: Topic

#658 Feature/idle whistling
  game/script-idles.rpy
  game/sprite-backend.rpy
Labels: Enhancement

#655 Feature/m1
  game/gifts.rpy
  game/mod_assets/poems/notepad.png
  game/mod_assets/props/confetti/confetti_a.png
  game/mod_assets/props/confetti/confetti_b.png
  game/mod_assets/props/confetti/confetti_c.png
  game/mod_assets/props/confetti/confetti_desk.png
  game/natsuki.rpy
  game/outfits.rpy
  game/relationship-handling.rpy
  game/screens.rpy
  game/script-events.rpy
  game/script-poems.rpy
  game/script-topics.rpy
  game/sprite-backend.rpy
Labels: High Priority, Topic

#660 switch to US spelling
  game/outfits.rpy
  game/script-events.rpy
  game/script-jokes.rpy
  game/script-topics.rpy
Labels: Bug

#656 v1.2.0
  .gitignore
  README.md
  game/activity.rpy
  game/custom-music.rpy
  game/definitions.rpy
  game/gifts.rpy
  game/gui.rpy
  game/locations.rpy
  game/mod_assets/buttons/check_selected_foreground.png
  game/mod_assets/furniture/classroom/beanbag_day.png
  game/mod_assets/furniture/classroom/beanbag_night.png
  game/mod_assets/natsuki/face/eyebrows/sitting/concerned.png
  game/mod_assets/natsuki/face/eyes/sitting/down.png
  game/mod_assets/natsuki/face/eyes/sitting/think_left.png
  game/mod_assets/natsuki/face/eyes/sitting/think_right.png
  game/mod_assets/natsuki/face/eyes/sitting/up.png
  game/mod_assets/natsuki/headgear/jn_headgear_cat_headphones/sitting.png
  game/mod_assets/natsuki/necklace/jn_necklace_black_choker/sitting.png
  game/mod_assets/poems/notepad.png
  game/mod_assets/props/confetti/confetti_a.png
  game/mod_assets/props/confetti/confetti_b.png
  game/mod_assets/props/confetti/confetti_c.png
  game/mod_assets/props/confetti/confetti_desk.png
  game/mod_assets/props/music/music_notes_a.png
  game/mod_assets/props/music/music_notes_b.png
  game/mod_assets/props/music/music_notes_c.png
  game/mod_assets/props/music/music_notes_d.png
  game/natsuki.rpy
  game/options.rpy
  game/outfits.rpy
  game/random_music.rpy
  game/relationship-handling.rpy
  game/screens.rpy
  game/script-admissions.rpy
  game/script-ch30.rpy
  game/script-events.rpy
  game/script-greetings.rpy
  game/script-idles.rpy
  game/script-jokes.rpy
  game/script-poems.rpy
  game/script-topics.rpy
  game/sprite-backend.rpy
  game/zz_data-migrations.rpy
Labels: Bug, Documentation, Enhancement, Major Update, Topic
